// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account/[path]" | "/admin" | "/admin/announcements-events" | "/admin/content" | "/admin/users" | "/ai-tutor" | "/assignments" | "/auth/[path]" | "/children" | "/collaboration" | "/dashboard" | "/dashboard/parent" | "/dashboard/student" | "/dashboard/tutor" | "/lessons/[id]" | "/login" | "/modules/[id]" | "/onboarding" | "/quizzes/[id]" | "/register" | "/search" | "/settings/accessibility" | "/subjects" | "/subjects/[id]" | "/verify"
type AppRouteHandlerRoutes = "/api/auth/[...path]" | "/api/auth/get-j-w-t-token"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account/[path]": { "path": string; }
  "/admin": {}
  "/admin/announcements-events": {}
  "/admin/content": {}
  "/admin/users": {}
  "/ai-tutor": {}
  "/api/auth/[...path]": { "path": string[]; }
  "/api/auth/get-j-w-t-token": {}
  "/assignments": {}
  "/auth/[path]": { "path": string; }
  "/children": {}
  "/collaboration": {}
  "/dashboard": {}
  "/dashboard/parent": {}
  "/dashboard/student": {}
  "/dashboard/tutor": {}
  "/lessons/[id]": { "id": string; }
  "/login": {}
  "/modules/[id]": { "id": string; }
  "/onboarding": {}
  "/quizzes/[id]": { "id": string; }
  "/register": {}
  "/search": {}
  "/settings/accessibility": {}
  "/subjects": {}
  "/subjects/[id]": { "id": string; }
  "/verify": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
